### ISSUE TITLE
can you add fetchRequest view support? 

### ISSUE THREAD

**Issue by bumpagram** [Mini-Stef/Core-Data-Model-Editor#12]
Hello mate. I bought this app in AppStore to give you some money for beer. 
It will be really nice to add, view and edit fetchRequests linked to Entities like it was in old Xcode DataModel-graph view. 
Really miss this function, we need this update. If it's too hard to realise, - at least to view fetchRequests with relationships just like other elements. 

----
and a little problem with app icon. It's bigger than others. Just asking to set it like others. Im perfectionist and its break my heart, haha. Look at screenshot
![Screenshot 2024-07-02 at 14 13 10](https://github.com/Mini-Stef/Core-Data-Model-Editor/assets/129959440/fdd687ef-353e-4089-8746-0be9ea0d1f75)

**Comment by Mini-Stef** [comment]
Hi there,
Yes, the fetch requests are on my todo list... and my todo list is quite long. I haven't had time enough those 3 last months to focus on the app, but I'll come back to it shortly, I promise.

Ho yeah, and I'll have a fix at the icon too :-)

Thanks for using the app !

Cheers

**Comment by bumpagram** [comment]
Cool, I will be waiting for fetchRequest view at least. Thank you for reply, Cheers! :)

**Comment by Mini-Stef** [comment]
Hello,
I am preparing the release of V1.3.0 (normally end of August).
I didn't add fetchRequest view yet (will be in 1.4.0), but I modified the icon size :-)

**Comment by vdhamer** [comment]
I think releasing regularly is great.
Shows you are active. And gets the software tested by users. The bug fix number in release name can also be used for smaller changes. At least that’s what I do.

Sent from my iPhone

On 4 Aug 2024, at 18:35, Mini-Stef ***@***.***> wrote:

﻿

Hello,
I am preparing the release of V1.3.0 (normally end of August).
I didn't add fetchRequest view yet (will be in 1.4.0), but I modified the icon size :-)

**Comment by Mini-Stef** [comment]
Hi,
I am working on revision 1.4.0 to be released before Christmas. It manages Fetch Requests.
I was surprised to see Fetch Requests have so many attributes (eg "Return Distinct Results"), but they're all managed.

The weak side is the input of the predicate. For the time being, it will be a text field, so you have to enter the exact correct predicate string. Surprisingly, there is no way to parse a predicate string to make sure it is correct (see answer to this https://stackoverflow.com/questions/53970414/how-to-validate-nspredicate-before-calling-fetch by Mr Tom Harrington himself), so I can't even verify the string syntax is correct.

In the next version I may be able to build a sound predicate editor, but that needs to real thinking.

**Comment by Mini-Stef** [comment]
I pushed version 1.4.1 this morning with the fetch request management.
I close this issue.

**Comment by Mini-Stef** [comment]
Hello. Apple takes a few days. But I think it is now on the App Store. I haven’t checked but I received a message. If you don’t have auto update enabled, you need to pull it from the AppStore. It’s free in all cases. Envoyé de mon iPhoneLe 9 déc. 2024 à 17:08, .b[u]mpagram ***@***.***> a écrit :﻿

I pushed version 1.4.1 this morning with the fetch request management. I close this issue.

hello. I don't receive new version. How much it takes for Apple to check and deliver your update to users of AppStore?

**Comment by bumpagram** [comment]
I saw update button on the product page in AppStore, but in Updates menu (with other Apps, which deploy new versions)  it’s not showing for some reason. Please check this.

**Comment by Mini-Stef** [comment]
Hello,

I am not sure to understand.

You see the "update" button in the product page. Right, so you can update from there.

But you don't see it in the "updates menu" (I guess that's the page with all updates when you select the Updates item in the left bar). Well, that's an AppStore app problem... there is nothing I can could. What I can tell for sure is that I clearly see version 1.4.1 being the latest version available on the App Store (and it's dated from 9 hours ago).

￼


Maybe CoreDat Model Editor is no longer installed on your mac, and that's why the AppStore don't offer you to update. Just re-download it.
