### ISSUE TITLE
Arrows present on diagram but line joining them is missing.

### ISSUE THREAD

**Issue by TS200010** [Mini-Stef/Core-Data-Model-Editor#13]
**Describe the bug**
Arrows present on digram but line joining them is missing.

**To Reproduce**
Not sure how to reproduce but will try and attach the offending model.

**Expected behavior**
The line should be there

**Screenshots**

**Desktop (please complete the following information):**
macOS Sonoma 14.1.1

<img width="1246" alt="Screenshot 2024-10-04 at 13 01 55" src="https://github.com/user-attachments/assets/6a6f6ceb-d37f-46de-bcae-e987562bb63c">

[DataModel.xcdatamodeld.zip](https://github.com/user-attachments/files/17252998/DataModel.xcdatamodeld.zip)

**Comment by TS200010** [comment]
That would explain what appeared to me to be an error. Thanks for taking the time to look at it. 

I have also just spent an hour rebuilding the xcdatamodel (no d) file as it suddenly stopped compiling after I think I saved it in error. The offending line was        
 <attribute name="answer" optional="YES" attributeType="String" defaultValueString=""""/> and its the four quotes causing the problem. Xcode puts &quot &quot not "" if that is what I enter as a default string.

I cannot be sure that they originated with your software but I mention it just win case.

Many thanks.

**Comment by Mini-Stef** [comment]
I will have a look at this 4 quotes story, it may come from the app indeed. But it’s now 8 am in my time zone, I am on the bus to go to work. I’ll look at it tonight 😀 Thanks again. Envoyé de mon iPhoneLe 4 oct. 2024 à 07:44, TS200010 ***@***.***> a écrit :﻿
That would explain what appeared to me to be an error. Thanks for taking the time to look at it.
I have also just spent an hour rebuilding the xcdatamodel (no d) file as it suddenly stopped compiling after I think I saved it in error. The offending line was
<attribute name="answer" optional="YES" attributeType="String" defaultValueString=""""/> and its the four quotes causing the problem. Xcode puts &quot &quot not "" if that is what I enter as a default string.
I cannot be sure that they originated with your software but I mention it just win case.
Many thanks.

**Comment by Mini-Stef** [comment]
OK, as I am starting a new version, I had a look at that 4 quotes story.
The only way I could find to reproduce the bug was to on-purpose set the default value at >>""<< (two quotes in the text field). Did you do that ?

Also, something strange is that when I look in your file, >>""<< doesn't exist. Instead, some text fields are set to >>&quot;&quot;<<, which my app translate into >>""<< when reading your file, and then writes back as """".
Now the question is where that >>&quot;&quot;<< comes from. As I absolutely don't use that, I guess it comes from another editor - maybe XCode.

I will add a protection that any " in a string is written back as &quot;, so you won't have the """" problem anymore.

**Comment by Mini-Stef** [comment]
Hi,
No, you don't need to do everything. What you say is the use case towards which I converged. So next version - which I hope to release before the end of the year - will not have that problem again.
Thanks !

**Comment by Mini-Stef** [comment]
I pushed version 1.4.1 this morning with the """" problem solved.
I close this issue.

**Comment by TS200010** [comment]
Thanks for letting me know.I’ll look at it next week.RegardsTonySent from my iPhoneOn 8 Dec 2024, at 09:09, Mini-Stef ***@***.***> wrote:﻿
I pushed version 1.4.1 this morning with the """" problem solved.
I close this issue.
