### ISSUE TITLE
Color picker sometimes updates color of multiple Configurations

### ISSUE THREAD

**Issue by vdhamer** [Mini-Stef/Core-Data-Model-Editor#14]
**Describe the bug**
I had a situation where the new color picker changes the colors of two Configurations simultaneously instead of just one. See Screenshots.

**Can user work around this?**
A user can work around the bug by deleting and recreating one of the Configurations.

**Steps to reproduce the behavior**
I used a schema file created using Xcode (so not edited with Core-Data-Model-Editor). This file doesn't contain color information, but did contain 3 Configurations, each mapped to 2 entities each.
I have attached the file (use version 2.7.1 - the latest schema version).
[Photo_Club_Hub.xcdatamodeld.zip](https://github.com/user-attachments/files/17967348/Photo_Club_Hub.xcdatamodeld.zip)
Then try to get a color mapping to resemble this (the chosen colors don’t matter).:

<img width="1075" alt="dataModel" src="https://github.com/user-attachments/assets/586dd6cf-2f3d-42c5-b133-fa44791a3df8">

**Expected behavior**
The color picker should only update the color of the configuration which has focus (extra - hard to see - outline around color box).

**Screenshots**
<img width="1505" alt="Screenshot 2024-12-01 at 01 08 15" src="https://github.com/user-attachments/assets/a51ecbcd-4cec-4286-9772-d1f04a6ba795">

**Software environment**
Latest released MacOS. Latest _beta_ of XCode. Versions probably not relevant.

**Comment by Mini-Stef** [comment]
Hello,

Thanks for the problem report.
I guess this is because both your configurations have the same name "Configuration_2".

This there is in fact only one configuration...

This said, having the same name shouldn't be allowed by the editor, and I also found that the Undo "set configuration color" was going back to the old colour in the diagram, but not in the colour picker.

i'll solve all that in next version.

Many thanks !

**Comment by vdhamer** [comment]
> Thanks for the problem report. I guess this is because both your configurations have the same name "Configuration_2".
> 
> This there is in fact only one configuration...
> 
> This said, having the same name shouldn't be allowed by the editor, and I also found that the Undo "set configuration color" was going back to the old colour in the diagram, but not in the colour picker.

Ahhh. So largely a preventable user error. So just fixing duplicate names while reading the data would indeed prevent this. Alternatively, your tool could just use its own identification (e.g. UUID) internally and thus just see the configuration name as a comment rather than an identifier.

But it is kind of weird, as the model used internally for the schema does allow you to assign (and store) lists of entities per configuration (instance), and the editor allows you to assign a color per instance, but it doesn’t propagate the correctly assigned colors to the correctly assigned entities.

All in all, not a big deal. Chances are few people will run into this, so any solution is fine. Does the tool actually use Core Data to store entities/relationships/properties?

**Comment by Mini-Stef** [comment]
> Does the tool actually use Core Data to store entities/relationships/properties?

No, it does not. There is no need for that, and it would need to have a Core Data Model description all the capabilities of Core Data Models... I am not that smart (and it would maybe create a breach in the universe continuum).

**Comment by Mini-Stef** [comment]
OK, it is no longer possible to have 2 configurations with the same name.
1) when reading a model with two same names, the second is appended a "_" (well, as many "_" as needed to be unique).
2) when trying to modify a configuration name to an existing one, the action is refused.

And by the way, I implemented the same for the Entity names :-)

**Comment by Mini-Stef** [comment]
I pushed version 1.4.1 this morning with name uniqueness management.
I close this issue.
