### ISSUE TITLE
Screenshots show ✣

### ISSUE THREAD

**Issue by vdhamer** [Mini-Stef/Core-Data-Model-Editor#15]
Since the last big update, the graphical representation will show a gray ✣ at the top of every entity.
This apparently solve some else's problem of not knowing where or how to drag the entities around.
But now a screenshot will also show this ✣ multiple times. And that screenshot may end up in [some documentation](https://github.com/vdhamer/Photo-Club-Hub#the-data-model). 
And apparently the ✣ shifts the entity title to the right.

![image](https://github.com/user-attachments/assets/b397f457-3a1d-418d-8e39-88b805e9bb13)

Not a big deal, but strictly speaking the unicode arrow is to help while editing, and not part of the graphical output.
In my case I use your fancy editor mainly as an image generator (layout, colors). And add entities and attributes in Xcode.

### Ideas about what can be done about this

- It is certainly an option to simply leave this as it is. It may simply not be worth fixing.
- Show the ✣ only when the cursor hovers over a rectangle. This may also help their intended purpose. Best solution?
- Add a checkbox to disable them (default enabled). So user can choose whether to see the ✣s manually. Easiest solution?
- Allow the color of the ✣ to be adjusted. Including a fully transparent color. Hmmm.
- Provide an export function that excludes them in the (PNG?) output. Hmmm.

**Comment by Mini-Stef** [comment]
Hello,
Thanks for the comment.
Next revision (1.4.0) will not show the ✣ in prints.

**Comment by Mini-Stef** [comment]
I pushed version 1.4.1 this morning with the drag cross removed from prints.
I close this issue.

**Comment by vdhamer** [comment]
Thank you for the various changes.

Sent from my iPad

On 8 Dec 2024, at 10:10, Mini-Stef ***@***.***> wrote:

﻿

Closed #15<https://github.com/Mini-Stef/Core-Data-Model-Editor/issues/15> as completed.

**Comment by vdhamer** [comment]
OK. So to get a screenshot without ✣s I should now:

- print to a PDF file, 
- open that file, 
- take a screenshot? ;-)

**Comment by Mini-Stef** [comment]
Well, presented like this... yes, it does not seem a smart move...

This said, a screen short is... an "exact" shot of the screen. And yes, the screen shows "edition helps", as it is an editor screen.
While the print only shows "content".

I think I'll add a PNG/PDF/JPEG export of the portion shown by the editor. Can you fill another issue for that please ?

**Comment by vdhamer** [comment]
Done: #23

It is an updated copy of this Issue.
