### ISSUE TITLE
Setting and saving colors for the entities

### ISSUE THREAD

**Issue by vdhamer** [Mini-Stef/Core-Data-Model-Editor#6]
The app allows entities to be assigned to Configurations, and configurations to be assigned colors:

- the user cannot directly control the color of an entity. It is set by assigning colours to a "**configuration**". Regardless of what Apple meant configurations for, this should work fine, especially if you have multiple entities per color. But...
- the user cannot directly **control the color of a given configuration**: if you want blue, you have to generate new configurations until you find one that is associated with blue. The app looks like it was prepared to allow you to choose a color using a color picker. This would help because there are only a few colors supported. And some are unsuitable for combining with white or with black font (depending on MacOS light or dark mode).
- I need to check if the colors are conveniently **persisted**, and whether the colors survive an editing round trip through Xcode. I saw that they are stored in an extra data file, so the app's intention is clearly to persist the colours, but I thought there was an issue there (sorry for fuzzy bullet: I will check and update this next time that I use your app).

Thanks for the v1.2.0 update! I am particularly happy that at some point you plan to support Swift Data as well.

**Comment by Mini-Stef** [comment]
Hello Peter,

Thank again for the remark.
I must admit colors management is quite "light" for the time being. The initial goal was to identify configurations easily in the graphical area, and I think it does the job... Except when an entity belongs to several configurations, in which case, only one color is shown.
And you are right, for the time being, the color can't be chosen (the button is disabled), and they are not really persistent. All in all, they will remain the same... until you delete a configuration and then restart the app. But again the goal was to quickly identify configurations, so...
I agree this deserves better, especially as I also wanted the color mechanism to show diff between versions of a model (which is in the to do list).

For the time being, I am working on the "undo" management, and validation of the fields (e.g. the tool should not allow an entity name to start with lowercase, and attributes name by uppercase etc...). Combining validation of text fields and undo is a pretty difficult task. Much more than it should be.

**Comment by vdhamer** [comment]
It is fine to give this low priority. Note that I use color to create a diagram and classify tables/entities per topic.
I didn't look up what Configuration was originally mean for.

"diffs between versions" - keep in mind that (especially with your new version) you should be able to see accurate diffs at the ASCII level in git/github.

Assuming you will be working on the app for while, you might want to send me your direct e-mail address.
You can find me on linkedIn or Facebook. There's nobody else with my name.

**Comment by Mini-Stef** [comment]
Linked-in invitation sent :-)

**Comment by Mini-Stef** [comment]
For information, started to work on the topic :-)

**Comment by Mini-Stef** [comment]
Done. Will be released with version 1.3.0 at the end of August
