### ISSUE TITLE
Improve layout of relationships if entities are above each other

### ISSUE THREAD

**Issue by vdhamer** [Mini-Stef/Core-Data-Model-Editor#7]
### Problem

If two entities are exactly or roughly above each other, a connecting relationship runs through the lowest entity's box.
This would also apply for relationships between an entity and itself (e.g. `parent` to `child` relations in a hierarchy of `Nodes`).

### Suggestion and Example

If `EntityL` is on the left and `EntityR` is clearly on the right, the rendering of the relationship connects `EntityL`.`rightSide` to `EntityR`.`leftSide`. This if fine.

But if `EntityB` is on the bottom and `EntityT` is on the top (but not clearly on the left or right), relationships should not connect `EntityB`.`rightSide` to `EntitiyT`.`leftSide` (or vice versa). Instead, it would be nicer to connect `EntityB`.`rightSide` and `EntitiyT`.`rightSide` (or `EntityB`.`leftSide` to `EntityT`.`leftSide`).

How to detect this? If the two boxes' x-ranges overlap.

How to choose which side? Choose the side with least amount of existing connections at that time (summed over both entities). In the example below, the connection between the two blue entities would then be on the right side rather than the left side. Global optimisation of avoiding crossing relationships might be possible, but require more work.

<img width="1023" alt="dataModel_to_be" src="https://github.com/Mini-Stef/Core-Data-Model-Editor/assets/13396568/0003a853-03ed-4210-b4e5-a08c95434a5c">

<img width="1110" alt="Screenshot 2024-01-22 at 00 41 17" src="https://github.com/Mini-Stef/Core-Data-Model-Editor/assets/13396568/0963cf25-dba8-480c-91b6-7597800a0525">

<img width="1109" alt="Screenshot 2024-01-22 at 00 40 31" src="https://github.com/Mini-Stef/Core-Data-Model-Editor/assets/13396568/b180c8bd-42fe-4028-875d-afdc56442c3d">

<img width="1019" alt="Screenshot 2024-01-22 at 00 50 01" src="https://github.com/Mini-Stef/Core-Data-Model-Editor/assets/13396568/5f9c5aa6-71cb-4681-a392-f4bbe5e714c8">

**Comment by Mini-Stef** [comment]
Hello,
Yes ! Will do in next version  :-)
Thanks again.

**Comment by Mini-Stef** [comment]
I did some stuff... It is not so simple in fact.
Looks like that:

<img width="767" alt="Capture d’écran 2024-12-07 à 23 22 02" src="https://github.com/user-attachments/assets/905c6f60-42f5-4a1e-8ba6-0f6e9ebe4459">

**Comment by Mini-Stef** [comment]
I pushed version 1.4.1 this morning with the above modification.
I close this issue.
