### ISSUE TITLE
Don't allow relationships to be their own inverse

### ISSUE THREAD

**Issue by vdhamer** [Mini-Stef/Core-Data-Model-Editor#8]
### Problem

A relationship between entity X.rel1 should not be allowed to select as inverse entity X.rel1

### Suggestion

Don't put entity X.rel1 in the pick list when selecting the inverse for entity X.rel1

### And what happens if you do choose that option?

- User can create this, giving this graphical representation.

> <img width="280" alt="Screenshot 2024-01-22 at 00 59 27" src="https://github.com/Mini-Stef/Core-Data-Model-Editor/assets/13396568/004b5034-c42f-4fcd-9e9e-0b7e916a6399">

- The data can be saved to disk.

- And the saved data can be loaded from disk by the app.
- And the data is then shown as above.

**Comment by Mini-Stef** [comment]
Hello,

Yes, this is part of the "validation" of model I intend to introduce in the next version.
Thanks,

**Comment by Mini-Stef** [comment]
Hello,

Solved in V1.3.0 to be relased end of August.
I close the issue.
